# Generated by Django 5.2 on 2026-07-13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("problem_slug", models.CharField(max_length=255)),
                ("problem_title", models.CharField(max_length=300)),
                ("frontend_id", models.CharField(blank=True, max_length=30)),
                ("difficulty", models.CharField(blank=True, max_length=10)),
                ("status", models.CharField(choices=[("started", "Started"), ("understood", "Understood"), ("brute_force", "Brute force"), ("solved", "Solved"), ("optimized", "Optimized"), ("mastered", "Mastered")], default="started", max_length=20)),
                ("confidence", models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ("mistake_category", models.CharField(blank=True, choices=[("", "Not recorded"), ("problem_understanding", "Problem understanding"), ("edge_case", "Edge case"), ("algorithm_choice", "Algorithm choice"), ("implementation", "Implementation"), ("complexity", "Complexity"), ("none", "No mistake")], default="", max_length=30)),
                ("reflection", models.TextField(blank=True, default="", max_length=4000)),
                ("review_stage", models.PositiveSmallIntegerField(default=0)),
                ("next_review_at", models.DateTimeField(blank=True, null=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("next_review_at", "pk"),
                "indexes": [models.Index(fields=["session_key", "next_review_at"], name="study_session_review_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("session_key", "problem_slug"), name="unique_study_record_per_session_problem"),
                    models.CheckConstraint(condition=models.Q(("confidence__gte", 1), ("confidence__lte", 5)), name="study_confidence_between_1_and_5"),
                    models.CheckConstraint(condition=models.Q(("review_stage__gte", 0)), name="study_review_stage_nonnegative"),
                ],
            },
        ),
    ]
